apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: 8-way-create
rules:
- apiGroups: ["*"]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["pods", "statefulsets", "daemonsets", "cronjobs", "jobs", "replicationcontrollers", "deployments", "replicasets"]
  verbs: ["get", "watch", "list", "create"]
