apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-demo
spec:
  serviceAccountName: thor
  containers:
  - name: secrets-demo
    image: nginx
    command: ["sleep", "infinity"]
  #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
