apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
spec:
  serviceAccountName: lucifer
  containers:
  - name: pod-privileged
    image: nginx
    securityContext:
      privileged: true
    command: ["tail", "-f", "/dev/null"]
  #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
