apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cluster-read-secret
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: thor
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-secrets-reader
  apiGroup: rbac.authorization.k8s.io
